routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['as' => 'front.', 'namespace' => 'FrontPanel'], function() {
    Route::post('feedbackStore', 'FeedbackController@store')->name('feedbackSubmit');
    Route::get('feedback', 'FeedbackController@show')->name('feedback');

    Route::group(['as' => 'pages.', 'prefix' => 'page'], function() {
        Route::get('travel', 'PagesController@travelPage')->name('travel');
        Route::get('estate', 'PagesController@estatePage')->name('estate');
        Route::get('auto', 'PagesController@autoPage')->name('auto');
    });

    Route::get('contacts', 'PagesController@contactsPage')->name('contacts');
    Route::get('about-us', 'PagesController@aboutUsPage')->name('aboutUs');

    Route::get('/', 'HomeController@index')->name('homepage');
});

Route::group(['as' => 'admin.', 'namespace' => 'AdminPanel', 'prefix' => 'admin-panel'], function() {
    Route::group(['middleware' => 'Admin'], function() {
        Route::resource('users', 'UserController');
        Route::resource('branch', 'BranchController');
        Route::resource('branch-workers', 'BranchWorkersController');
        Route::resource('feedback', 'FeedbackController');
        Route::resource('insurance-type', 'InsuranceTypeController');
        Route::resource('user-documents', 'UserDocumentController');
        Route::resource('contracts', 'ContractController');
    });
});

resources/views/admin-layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    @yield('css')
</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Control</h4>
                    <ul class="list-unstyled">
                        @guest
                            <li><a href="{{ route('login') }}" class="text-white">Login</a></li>
                        @else
                            <li>
                                <form action="{{ route('logout') }}" method="POST">
                                    @csrf
                                    <button type="submit" hidden id="go_logout"></button>
                                    <label for="go_logout">
                                        <a class="text-white">Exit</a>
                                    </label>
                                </form>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{{ route('admin.users.index') }}" class="navbar-brand d-flex align-items-center">
                <strong>Пользователи</strong>
            </a>
            <a href="{{ route('admin.feedback.index') }}" class="navbar-brand d-flex align-items-center">
                <strong>Обратная связь</strong>
            </a>
            <a href="{{ route('admin.insurance-type.index') }}" class="navbar-brand d-flex align-items-center">
                <strong>Типы страховок</strong>
            </a>
            <a href="{{ route('admin.branch.index') }}" class="navbar-brand d-flex align-items-center">
                <strong>Филиалы</strong>
            </a>
            <a href="{{ route('admin.contracts.index') }}" class="navbar-brand d-flex align-items-center">
                <strong>Договора</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>


<main role="main">
    @yield('content')
</main>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

@yield('scripts')

<script>
    $(document).ready(function() {
        @if(Session::has('success'))
        toastr.success('{{ Session::get('success') }}');
        @elseif(Session::has('error'))
        toastr.error('{{ Session::get('error') }}');
        @endif
    });
</script>
</body>
</html>