routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['as' => 'front.', 'namespace' => 'FrontPanel'], function() {
    Route::post('feedbackStore', 'FeedbackController@store')->name('feedbackSubmit');
    Route::get('feedback', 'FeedbackController@show')->name('feedback');

    Route::group(['as' => 'pages.', 'prefix' => 'page'], function() {
        Route::get('travel', 'PagesController@travelPage')->name('travel');
        Route::get('estate', 'PagesController@estatePage')->name('estate');
        Route::get('auto', 'PagesController@autoPage')->name('auto');
    });

    Route::get('contacts', 'PagesController@contactsPage')->name('contacts');
    Route::get('about-us', 'PagesController@aboutUsPage')->name('aboutUs');

    Route::get('/', 'HomeController@index')->name('homepage');
});

Route::group(['as' => 'admin.', 'namespace' => 'AdminPanel', 'prefix' => 'admin-panel'], function() {
    Route::group(['middleware' => 'Admin'], function() {
        Route::resource('users', 'UserController');
        Route::resource('branch', 'BranchController');
        Route::resource('branch-workers', 'BranchWorkersController');
        Route::resource('feedback', 'FeedbackController');
        Route::resource('insurance-type', 'InsuranceTypeController');
        Route::resource('user-documents', 'UserDocumentController');
        Route::resource('contracts', 'ContractController');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password', 'first_name', 'last_name', 'is_admin', 'phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminPanel/UserController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Business\Models\BranchWorkers;
use App\Business\Models\Contracts;
use App\Business\Models\UserDocuments;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index(User $users)
    {
        $users = $users->paginate(20);
        return view('admin-layouts.users.index', compact('users'));
    }

    public function create()
    {
        return view('admin-layouts.users.create');
    }

    public function store(CreateUserRequest $request, User $user, UserDocuments $userDocuments)
    {
        $user = $user->create($request->except(['_token']));
        $userDocuments->create(['user_id' => $user->id]);
        return redirect()->route('admin.users.show', $user);
    }

    public function show(User $user)
    {
        return view('admin-layouts.users.show', compact('user'));
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        $data = $request->all();
        if ($request->new_password) {
            $data['password'] = Hash::make($request->new_password);
        }
        $user->fill($data);
        $user->save();
        return redirect()->back()->with('success', 'Данные успешно сохранены.');
    }

    public function destroy(User $user, UserDocuments $userDocuments, Contracts $contracts, BranchWorkers $branchWorkers)
    {
        $userDocuments->where('user_id', $user->id)->delete();
        $contracts->where('client_id', $user->id)->delete();
        if ($user->is_admin) {
            $branchWorkers->where('worker_id', $user->id)->delete();
        }
        $user->delete();
        return redirect()->route('admin.users.index')->with('success', 'Пользователь успешно удален');
    }
}

resources/views/admin-layouts/users/create.blade.php
@extends('admin-layouts.master')

@section('title', 'Добавление пользователя')

@section('content')
    <div class="container">
        <div class="py-5 text-center">
            <h2>Добавление пользователя</h2>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <form class="needs-validation" autocomplete="off" method="POST" action="{{ route('admin.users.store') }}">
                    @csrf
                    @include('admin-layouts.users.fields')
                    <hr class="mb-4">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Создать пользователя</button>
                </form>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script>
        $(document).ready(function() {
            @if ($errors->any())
            @foreach ($errors->all() as $error)
            toastr.error('{{ $error }}');
            @endforeach
            @endif
        });
    </script>
@stop

resources/views/admin-layouts/users/fields.blade.php
<div class="row">
    <div class="col-md-6 mb-3">
        <label for="name">Имя</label>
        <input type="text" class="form-control" value="{{ old('first_name', $user->first_name ?? '') }}" name="first_name" id="name" placeholder="">
    </div>
    <div class="col-md-6 mb-3">
        <label for="price">Фамилия</label>
        <input type="text" class="form-control" name="last_name" id="price" placeholder="" value="{{ old('last_name', $user->last_name ?? '') }}">
    </div>
    <div class="col-md-6 mb-3">
        <label for="price">Номер телефона</label>
        <input type="text" class="form-control" name="phone" id="price" placeholder="" value="{{ old('phone', $user->phone ?? '') }}">
    </div>
    <div class="col-md-6 mb-3">
        <label for="price">Емайл</label>
        <input type="text" class="form-control" name="email" id="price" placeholder="" value="{{ old('email', $user->email ?? '') }}">
    </div>
    <div class="col-md-6 mb-3">
        <label for="price">Пароль</label>
        <input type="text" class="form-control" name="{{ isset($user) && $user->password ? 'new_password' : 'password' }}" id="price" placeholder="Введите чтобы изменить пароль">
    </div>

    <div class="col-md-6 mb-3">
        <label for="price">Тип пользователя</label>
        <select name="is_admin" class="form-control">
            <option @if(isset($user) && $user->is_admin) selected="selected" @endif value="1">Администратор</option>
            <option @if(isset($user) && !$user->is_admin) selected="selected" @endif value="0">Клиент</option>
        </select>
    </div>
</div>

resources/views/admin-layouts/users/index.blade.php
@extends('admin-layouts.master')

@section('title', 'Users')

@section('content')
    <div class="container">
        <div class="py-5 text-center">
            <h2>Пользователи</h2>
        </div>

        <div class="row">
            <div class="col-md-12 text-right mb-5">
                <a href="{{ route('admin.users.create') }}" class="btn btn-primary">Добавить пользователя</a>
            </div>
        </div>
        <div class="row">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Номер телефона</th>
                    <th scope="col">Email</th>
                </tr>
                </thead>
                <tbody>
                @if(count($users))
                    @foreach($users as $user)
                        <tr onclick="window.location.href = '{{ route('admin.users.show', $user) }}'">
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->first_name }}</td>
                            <td>{{ $user->last_name ?? 'Не определено' }}</td>
                            <td>{{ $user->phone ?? 'Не определено' }}</td>
                            <td>{{ $user->email ?? 'Не определено' }}</td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="5">Пользователей не найдено</td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/admin-layouts/users/show.blade.php
@extends('admin-layouts.master')

@section('title', 'Пользователь #' . $user->id)

@section('content')
    <div class="container">
        <div class="py-5 text-center">
            <h2>Редактирование информации о пользователе</h2>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <form class="needs-validation" autocomplete="off" method="POST" action="{{ route('admin.users.update', $user) }}">
                    @csrf
                    @method('PUT')
                    @include('admin-layouts.users.fields')
                    <hr class="mb-4">
                    <div class="row">
                        <div class="col-md-6">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Обновить пользователя</button>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ route('admin.user-documents.show', $user) }}" class="btn btn-warning btn-lg btn-block">Документы пользователя</a>
                        </div>
                    </div>
                </form>
                <form action="{{ route('admin.users.destroy', $user) }}" method="POST" onsubmit="return confirm('Вы действительно хотите удалить данного пользователя?');">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger mt-2 btn-lg btn-block" type="submit">Удалить пользователя</button>
                </form>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script>
        $(document).ready(function() {
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    toastr.error('{{ $error }}');
                @endforeach
            @endif
        });
    </script>
@stop