routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['as' => 'front.', 'namespace' => 'FrontPanel'], function() {
    Route::post('feedbackStore', 'FeedbackController@store')->name('feedbackSubmit');
    Route::get('feedback', 'FeedbackController@show')->name('feedback');

    Route::group(['as' => 'pages.', 'prefix' => 'page'], function() {
        Route::get('travel', 'PagesController@travelPage')->name('travel');
        Route::get('estate', 'PagesController@estatePage')->name('estate');
        Route::get('auto', 'PagesController@autoPage')->name('auto');
    });

    Route::get('contacts', 'PagesController@contactsPage')->name('contacts');
    Route::get('about-us', 'PagesController@aboutUsPage')->name('aboutUs');

    Route::get('/', 'HomeController@index')->name('homepage');
});

Route::group(['as' => 'admin.', 'namespace' => 'AdminPanel', 'prefix' => 'admin-panel'], function() {
    Route::group(['middleware' => 'Admin'], function() {
        Route::resource('users', 'UserController');
        Route::resource('branch', 'BranchController');
        Route::resource('branch-workers', 'BranchWorkersController');
        Route::resource('feedback', 'FeedbackController');
        Route::resource('insurance-type', 'InsuranceTypeController');
        Route::resource('user-documents', 'UserDocumentController');
        Route::resource('contracts', 'ContractController');
    });
});

app/Http/Controllers/AdminPanel/BranchController.php
<?php

namespace App\Http\Controllers\AdminPanel;

use App\Business\Models\Branch;
use App\Http\Controllers\Controller;
use App\Http\Requests\BranchRequest;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    public function index(Branch $branch)
    {
        $branches = $branch->paginate(20);
        return view('admin-layouts.branch.index', compact('branches'));
    }

    public function show(Branch $branch)
    {
        return view('admin-layouts.branch.show', compact('branch'));
    }

    public function create()
    {
        return view('admin-layouts.branch.create');
    }

    public function store(BranchRequest $request, Branch $branch)
    {
        $branch = $branch->create($request->except('_token'));
        return redirect()->route('admin.branch.show', $branch);
    }

    public function update(BranchRequest $request, Branch $branch)
    {
        $branch->fill($request->all());
        $branch->save();
        return redirect()->back()->with('success', 'Филиал успешно сохранен');
    }
}

resources/views/admin-layouts/branch/create.blade.php
@extends('admin-layouts.master')

@section('title', 'Добавление филиала')

@section('content')
    <div class="container">
        <div class="py-5 text-center">
            <h2>Добавление информации о филиале</h2>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <form class="needs-validation" autocomplete="off" method="POST" action="{{ route('admin.branch.store') }}">
                    @csrf
                    @include('admin-layouts.branch.fields')
                    <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Создать филиал</button>
                </form>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script>
        $(document).ready(function() {
            @if ($errors->any())
            @foreach ($errors->all() as $error)
            toastr.error('{{ $error }}');
            @endforeach
            @endif
        });
    </script>
@stop

resources/views/admin-layouts/branch/fields.blade.php
<div class="row">
    <div class="col-md-6 mb-3">
        <label for="name">Название</label>
        <input type="text" class="form-control" value="{{ old('name', $branch->name ?? '') }}" name="name" id="name" placeholder="">
    </div>
    <div class="col-md-6 mb-3">
        <label for="price">Номер телефона</label>
        <input type="text" class="form-control" name="phone" id="price" placeholder="" value="{{ old('phone', $branch->phone ?? '') }}">
    </div>
    <div class="col-md-12 mb-3">
        <label for="price">Адрес</label>
        <input type="text" class="form-control" name="address" id="price" placeholder="" value="{{ old('address', $branch->address ?? '') }}">
    </div>
</div>

resources/views/admin-layouts/branch/index.blade.php
@extends('admin-layouts.master')

@section('title', 'Филиалы')

@section('content')
    <div class="container">
        <div class="py-5 text-center">
            <h2>Филиалы</h2>
        </div>

        <div class="row">
            <div class="col-md-12 text-right mb-5">
                <a href="{{ route('admin.branch.create') }}" class="btn btn-primary">Добавить филиал</a>
            </div>
        </div>
        <div class="row">
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col">Номер телефона</th>
                    <th scope="col">Адрес</th>
                </tr>
                </thead>
                <tbody>
                @if(count($branches))
                    @foreach($branches as $branch)
                        <tr onclick="window.location.href = '{{ route('admin.branch.show', $branch) }}'">
                            <th scope="row">{{ $branch->id }}</th>
                            <td>{{ $branch->name }}</td>
                            <td>{{ $branch->phone ?? 'Не определено' }}</td>
                            <td>{{ $branch->address ?? 'Не определено' }}</td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="5">Филиалов не найдено</td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/admin-layouts/branch/show.blade.php
@extends('admin-layouts.master')

@section('title', 'Филиал #' . $branch->id)

@section('content')
    <div class="container">
        <div class="py-5 text-center">
            <h2>Редактирование информации о филиале</h2>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <form class="needs-validation" autocomplete="off" method="POST" action="{{ route('admin.branch.update', $branch) }}">
                    @csrf
                    @method('PUT')
                    @include('admin-layouts.branch.fields')
                    <hr class="mb-4">
                    <div class="row">
                        <div class="col-md-6">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Обновить филиал</button>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ route('admin.branch-workers.show', $branch) }}" class="btn btn-warning btn-lg btn-block">Работники филиала</a>
                        </div>
                    </div>
                </form>
                <form action="{{ route('admin.branch.destroy', $branch) }}" method="POST" onsubmit="return confirm('Вы действительно хотите удалить данный филиал?');">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger mt-2 btn-lg btn-block" type="submit">Удалить филиал</button>
                </form>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script>
        $(document).ready(function() {
            @if ($errors->any())
            @foreach ($errors->all() as $error)
            toastr.error('{{ $error }}');
            @endforeach
            @endif
        });
    </script>
@stop